name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        platform:
        - { name: Windows,     os: windows-latest, preset: x64-release-windows, flags:  }
        - { name: Linux GCC,   os: ubuntu-latest,  preset: x64-release-linux,   flags: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ }
        - { name: Linux Clang, os: ubuntu-latest,  preset: x64-release-linux,   flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev

    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake --preset ${{ matrix.platform.preset }}
        ${{ matrix.platform.flags }}
        -B build
        -DCMAKE_INSTALL_PREFIX=install

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest --test-dir build

    - name: Install
      run: cmake --install build --config Release
